### ISSUE TITLE
Error processing historical data ( BASIC-1.133485839 )

### ISSUE THREAD

**Issue by oughtotrade** [liampauling/betfair#131]
event type id: 7 (Horse Racing)
country code: AU
Market id: 1.133485839
market type: WIN
date: 24/8/2017
filename: BASIC-1.133485839

This market is available for free download from historicdata.betfair.com

While processing the historical stream in this file, betfairlightweight encounters the following error:
```
INFO:betfairlightweight.streaming.stream:[Stream: None]: "MarketStream" created
INFO:betfairlightweight.streaming.stream:[MarketStream: HISTORICAL] 1.133485839 added
Traceback (most recent call last):
  File "run_bf_backtest.py", line 122, in <module>
    stream.start(async=False)
  File "/home/x/.virtualenvs/bfl-historical/local/lib/python2.7/site-packages/betfairlightweight/streaming/betfairstream.py", line 272, in start
    self._read_loop()
  File "/home/x/.virtualenvs/bfl-historical/local/lib/python2.7/site-packages/betfairlightweight/streaming/betfairstream.py", line 277, in _read_loop
    self.listener.on_data(update)
  File "/home/x/.virtualenvs/bfl-historical/local/lib/python2.7/site-packages/betfairlightweight/streaming/listener.py", line 115, in on_data
    self._on_change_message(data, unique_id)
  File "/home/x/.virtualenvs/bfl-historical/local/lib/python2.7/site-packages/betfairlightweight/streaming/listener.py", line 146, in _on_change_message
    self.stream.on_update(data)
  File "/home/x/.virtualenvs/bfl-historical/local/lib/python2.7/site-packages/betfairlightweight/streaming/stream.py", line 55, in on_update
    self._process(data[self._lookup], publish_time)
  File "/home/x/.virtualenvs/bfl-historical/local/lib/python2.7/site-packages/betfairlightweight/streaming/stream.py", line 133, in _process
    market_book_cache.create_resource(self.unique_id, market_book, self._lightweight)
  File "/home/x/.virtualenvs/bfl-historical/local/lib/python2.7/site-packages/betfairlightweight/resources/streamingresources.py", line 349, in create_resource
    **self.serialise
  File "/home/x/.virtualenvs/bfl-historical/local/lib/python2.7/site-packages/betfairlightweight/resources/streamingresources.py", line 383, in serialise
    ) for runner in self.runners
KeyError: (11993830, 0)
```
Not really sure what's going on, but I'm on hand to help with any further debugging if required.

Thanks.

**Comment by liampauling** [comment]
This looks to be an error with the data from betfair:

`DEBUG:betfairlightweight.streaming.listener:[Subscription: None]: UPDATE: {'mc': [{'id': '1.133485839', 'marketDefinition': {'name': 'R4 2140m Pace M', 'betDelay': 1, 'crossMatching': False, 'inPlay': True, 'marketType': 'WIN', 'discountAllowed': True, 'timezone': 'Australia/Sydney', 'numberOfWinners': 1, 'persistenceEnabled': True, 'bspMarket': True, 'turnInPlayEnabled': True, 'eventId': '28357818', 'openDate': '2017-08-24T08:17:00.000Z', 'eventName': 'Bank (AUS) 24th Aug', 'settledTime': '2017-08-24T09:50:24.000Z', 'runners': [{'sortPriority': 1, 'name': '3. Rocky Floyd', 'removalDate': '2017-08-23T23:20:15.000Z', 'id': 9403745, 'status': 'REMOVED', 'adjustmentFactor': 1.38}], 'venue': 'Bankstown', 'numberOfActiveRunners': 0, 'marketBaseRate': 8.0, 'runnersVoidable': False, 'marketTime': '2017-08-24T09:45:00.000Z', 'regulators': ['MR_INT'], 'complete': True, 'suspendTime': '2017-08-24T09:45:00.000Z', 'bettingType': 'ODDS', 'countryCode': 'AU', 'status': 'CLOSED', 'eventTypeId': '7', 'version': 1740153583, 'bspReconciled': True}}], 'clk': '5001464962', 'op': 'mcm', 'pt': 1503568253597}`

As you can see above a market definition update arrives but it only contains one runner which is a now removed instead of all 7:

` 'runners': [{'sortPriority': 1, 'name': '3. Rocky Floyd', 'removalDate': '2017-08-23T23:20:15.000Z', 'id': 9403745, 'status': 'REMOVED', 'adjustmentFactor': 1.38}],`

In the docs it states:

> marketDefinition / MarketDefinition - this is sent in full (but only if it has changed)

**Comment by oughtotrade** [comment]
Thanks, that makes sense. I will just delete this market from my computer, but no further action required on betfairlightweight?

**Comment by liampauling** [comment]
Yeh nothing we can really do as I wouldn't want to try and catch this error

**Comment by oughtotrade** [comment]
OK, I'll close the issue.
