### ISSUE TITLE
Resources can't handle missing fields from Betfair

### ISSUE THREAD

**Issue by agberk** [liampauling/betfair#95]
The following MarketCatalogue JSON was received from Betfair and caused the following error:

```
{
	"marketStartTime": "2017-06-06T09:00:00.000Z",
	"competition": {
		"id": "11330922",
		"name": "Prostejov Challenger 2017"
	},
	"marketId": "1.132045327",
	"totalMatched": 17.06,
	"marketName": "Match Odds",
	"event": {
		"timezone": "UTC",
		"openDate": "2017-06-06T09:00:00.000Z",
		"id": "28260245",
		"countryCode": "CZ",
		"name": "Marrero/Paes v Knowle/Zelenay"
	},
	"runners": [
		{
			"handicap": 0,
			"runnerName": "Knowle/Zelenay",
			"selectionId": 5717065,
			"sortPriority": 1
		},
		{
			"handicap": 0,
			"runnerName": "Marrero/Paes.",
			"selectionId": 8786145,
			"sortPriority": 2
		},
		{
			"handicap": 0,
			"sortPriority": 3,
			"selectionId": 8781561
		}
	]
}
```

```python
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/aaron/workspace/sportsrisq.traderng/sportsrisq/traderng/feed/betfair_market_feed.py", line 42, in betfair_market_feed
    locale=config.get('markets', {}).get('locale')
  File "/home/aaron/tmp/venv/betfairlightweight/local/lib/python2.7/site-packages/betfairlightweight/endpoints/betting.py", line 158, in list_market_catalogue
    return self.process_response(response, resources.MarketCatalogue, elapsed_time, lightweight)
  File "/home/aaron/tmp/venv/betfairlightweight/local/lib/python2.7/site-packages/betfairlightweight/endpoints/baseendpoint.py", line 100, in process_response
    return [resource(elapsed_time=elapsed_time, **x) for x in result]
  File "/home/aaron/tmp/venv/betfairlightweight/local/lib/python2.7/site-packages/betfairlightweight/resources/bettingresources.py", line 231, in __init__
    self.runners = [RunnerCatalogue(**i) for i in kwargs.get('runners', [])]
TypeError: __init__() takes at least 5 arguments (4 given)
```

The third runner is missing the runnerName field - which is listed a required field in the Betfair API docs: http://docs.developer.betfair.com/docs/display/1smk3cen4v3lu3yomq5qye0ni/Betting+Type+Definitions#BettingTypeDefinitions-RunnerCatalog

Because of this (and I think rightly so) the constructor for a RunnerCatalogue doesn't have a default value for runnerName: https://github.com/liampauling/betfairlightweight/blob/master/betfairlightweight/resources/bettingresources.py#L190-L195

I'm not really sure what the solution is here - maybe it's just to do nothing and accept that Betfair sends malformed data sometimes - however that will cause a listMarketCatalogue call to error in the above way. If all you want is the JSON then you can avoid it by using the `lightweight` parameter in the API call.

I have raised a ticket with BDP but I imagine the response will be it was just a mistake.

The bigger question is whether resources should handle fields which are missing which are listed as required in the API specification? It's also a question which I don't have the answer to :)

**Comment by agberk** [comment]
From BDP:

> Hi Aaron,
> 
> I have had a reply from our market operators, there was an issue when loading up the runners and they were not visible on site so we had to manually add the runners with a (DOT) at the end.
> 
> Please observe that the two ‘real’ runners have a RunnerStatus of ACTIVE and the ‘dead’ one of LOSER; The option would be to amend your market validation to only count ACTIVE runners.
> 
> This does seem like a very rare occurrence and we will monitor this moving forward.
> 
> Kind Regards,
> 
> Anthony.
